language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.6.8
  - gem --version
