---
chihaya:
  idol_id: 2
  idol_type: Fairy
  name:
    family: 如月
    family_kana: きさらぎ
    given: 千早
    given_kana: ちはや
    shorten: 千早
  age: 16
  height: 162.0
  weight: 41.0
  bust: 72.0
  waist: 55.0
  hip: 78.0
  birthday: 02/25
  blood_type: A
  handedness: right
  hobbies:
  - 音楽鑑賞
  talents:
  - 歌
  favorites:
  - トレーニング
  color: "#2743d2"
  cv: 今井麻美
  birthplace: 東京都
  idol_image: Vocal
