takane:
  idol_id: 8
  idol_type: Vo
  name:
    family: "四条"
    family_kana: "しじょう"
    given: "貴音"
    given_kana: "たかね"
    shorten: "貴音"
  age: 18
  height: 169.0
  weight: 49.0
  bust: 90.0
  waist: 62.0
  hip: 92.0
  birthday: 01/21
  blood_type: B
  handedness: right
  hobbies:
  - "天体観測"
  - "歴史"
  talents:
  - "直感"
  favorites:
  - "ラーメン"
  color: "#a6126a"
  cv: 原由実
