---
mami:
  idol_id: 12
  idol_type: Angel
  name:
    family: 双海
    family_kana: ふたみ
    given: 真美
    given_kana: まみ
    shorten: 真美
  age: 13
  height: 158.0
  weight: 42.0
  bust: 78.0
  waist: 55.0
  hip: 77.0
  birthday: 05/22
  blood_type: B
  handedness: left
  hobbies:
  - メール
  - ゲーム
  talents:
  - モノマネ
  favorites:
  - 遊ぶこと
  color: "#ffe43f"
  cv: 下田麻美
  birthplace: 東京都
  idol_image: Visual
