---
mirai:
  idol_id: 14
  idol_type: Princess
  name:
    family: 春日
    family_kana: かすが
    given: 未来
    given_kana: みらい
    shorten: 未来
  age: 14
  height: 156.0
  weight: 42.0
  bust: 78.0
  waist: 54.0
  hip: 77.0
  birthday: 06/28
  blood_type: O
  handedness: right
  hobbies:
  - 可愛い髪留めを集めること
  talents:
  - 歌うこと
  favorites:
  - ライブ
  color: "#ea5b76"
  cv: 山崎はるか
  birthplace: 東京都
  idol_image: Vocal
