---
erena:
  idol_id: 18
  idol_type: Angel
  name:
    family: 島原
    family_kana: しまばら
    given: エレナ
    given_kana: えれな
    shorten: エレナ
  age: 17
  height: 160.0
  weight: 47.0
  bust: 85.0
  waist: 58.0
  hip: 86.0
  birthday: 10/26
  blood_type: B
  handedness: right
  hobbies:
  - パーティー
  talents:
  - サンバを踊ること
  favorites:
  - みんなで騒ぐこと
  color: "#9bce92"
  cv: 角元明日香
  birthplace: ブラジル
  idol_image: Dance
