minako:
  idol_id: 19
  idol_type: Da
  name:
    family: "佐竹"
    family_kana: "さたけ"
    given: "美奈子"
    given_kana: "みなこ"
    shorten: "美奈子"
  age: 18
  height: 158.0
  weight: 45.0
  bust: 86.0
  waist: 54.0
  hip: 82.0
  birthday: 03/22
  blood_type: O
  handedness: right
  hobbies:
  - "格闘ゲーム"
  talents:
  - "料理"
  favorites:
  - "友達との長電話"
  color: "#58a6dc"
  cv: 大関英里
