---
matsuri:
  idol_id: 21
  idol_type: Princess
  name:
    family: 徳川
    family_kana: とくがわ
    given: まつり
    given_kana: まつり
    shorten: まつり
  age: 19
  height: 163.0
  weight: 44.0
  bust: 85.0
  waist: 59.0
  hip: 85.0
  birthday: 02/04
  blood_type: AB
  handedness: right
  hobbies:
  - 漫画あつめ
  talents:
  - 演技
  favorites:
  - 焼きマシュマロ
  - ウミウシ
  color: "#5abfb7"
  cv: 諏訪彩花
  birthplace: 愛知県
  idol_image: Visual
