sayoko:
  idol_id: 27
  idol_type: Vo
  name:
    family: "高山"
    family_kana: "たかやま"
    given: "紗代子"
    given_kana: "さよこ"
    shorten: "紗代子"
  age: 17
  height: 156.0
  weight: 42.0
  bust: 82.0
  waist: 55.0
  hip: 80.0
  birthday: 12/29
  blood_type: A
  handedness: right
  hobbies:
  - "ハリネズミの飼育"
  talents:
  - "一晩寝ると元気になれる"
  favorites:
  - "友達"
  - "アイドル仲間"
  color: "#7f6575"
  cv: 駒形友梨
