tomoka:
  idol_id: 31
  idol_type: Vo
  name:
    family: "天空橋"
    family_kana: "てんくうばし"
    given: "朋花"
    given_kana: "ともか"
    shorten: "朋花"
  age: 15
  height: 156.0
  weight: 41.0
  bust: 80.0
  waist: 56.0
  hip: 79.0
  birthday: 11/11
  blood_type: AB
  handedness: left
  hobbies:
  - "ファンに喜んでもらうこと"
  talents:
  - "口げんか"
  favorites:
  - "かわいい扇子"
  color: "#bee3e3"
  cv: 小岩井ことり
