chiduru:
  idol_id: 38
  idol_type: Vi
  name:
    family: "二階堂"
    family_kana: "にかいどう"
    given: "千鶴"
    given_kana: "ちづる"
    shorten: "千鶴"
  age: 21
  height: 165.0
  weight: 50.0
  bust: 85.0
  waist: 58.0
  hip: 86.0
  birthday: 10/21
  blood_type: B
  handedness: right
  hobbies:
  - "カフェでアパレル誌チェック"
  talents:
  - "人の名前と顔を忘れない"
  favorites:
  - "憧れの目で見られること"
  color: "#f19557"
  cv: 野村香菜子
