mizuki:
  idol_id: 44
  idol_type: Da
  name:
    family: "真壁"
    family_kana: "まかべ"
    given: "瑞希"
    given_kana: "みずき"
    shorten: "瑞希"
  age: 17
  height: 160.0
  weight: 43.0
  bust: 73.0
  waist: 54.0
  hip: 77.0
  birthday: 01/27
  blood_type: B
  handedness: right
  hobbies:
  - "手品"
  talents:
  - "バトントワリング"
  favorites:
  - "クロスワードパズル"
  color: "#99b7dc"
  cv: 阿部里果
