kaori:
  idol_id: 52
  idol_type:
  name:
    family: "桜守"
    family_kana: "さくらもり"
    given: "歌織"
    given_kana: "かおり"
    shorten: "歌織"
  age: 23
  height: 165.0
  weight: 47.0
  bust: 88.0
  waist: 58.0
  hip: 85.0
  birthday: 03/27
  blood_type: O
  handedness: right
  hobbies:
  - "乗馬"
  talents:
  - "合唱"
  - "ゴルフ"
  favorites:
  - "子ども"
  - "洋菓子"
  color: "#28417d"
  cv: 香里有佐
