---
haruka:
  idol_id: 1
  idol_type: Vo
  name:
    family: "天海"
    family_kana: "あまみ"
    given: "春香"
    given_kana: "はるか"
    shorten: "春香"
  age: 17
  height: 158.0
  weight: 46.0
  bust: 83.0
  waist: 56.0
  hip: 82.0
  birthday: 04/03
  blood_type: O
  handedness: right
  hobbies:
  - "カラオケ"
  - "長電話"
  talents:
  - "お菓子作り"
  favorites:
  - "歌うこと"
  color: "#e22b30"
chihaya:
  idol_id: 2
  idol_type: Vo
  name:
    family: "如月"
    family_kana: "きさらぎ"
    given: "千早"
    given_kana: "ちはや"
    shorten: "千早"
  age: 16
  height: 162.0
  weight: 41.0
  bust: 72.0
  waist: 55.0
  hip: 78.0
  birthday: 02/25
  blood_type: A
  handedness: right
  hobbies:
  - "音楽鑑賞"
  talents:
  - "歌"
  favorites:
  - "トレーニング"
  color: "#2743d2"
miki:
  idol_id: 3
  idol_type: Vi
  name:
    family: "星井"
    family_kana: "ほしい"
    given: "美希"
    given_kana: "みき"
    shorten: "美希"
  age: 15
  height: 161.0
  weight: 45.0
  bust: 86.0
  waist: 55.0
  hip: 83.0
  birthday: 11/23
  blood_type: B
  handedness: right
  hobbies:
  - "友達とおしゃべり"
  - "ネイルアート"
  talents:
  - "寝ること"
  favorites:
  - "おにぎり"
  - "いちごババロア"
  color: "#b4e04b"
yukiho:
  idol_id: 4
  idol_type: Vi
  name:
    family: "萩原"
    family_kana: "はぎわら"
    given: "雪歩"
    given_kana: "ゆきほ"
    shorten: "雪歩"
  age: 17
  height: 155.0
  weight: 42.0
  bust: 81.0
  waist: 56.0
  hip: 81.0
  birthday: 12/24
  blood_type: A
  handedness: right
  hobbies:
  - MY詩集を書くこと
  talents:
  - "日本茶をいれること"
  favorites:
  - "ブログ"
  color: "#d3dde9"
yayoi:
  idol_id: 5
  idol_type: Da
  name:
    family: "高槻"
    family_kana: "たかつき"
    given: "やよい"
    given_kana: "やよい"
    shorten: "やよい"
  age: 14
  height: 145.0
  weight: 37.0
  bust: 74.0
  waist: 54.0
  hip: 78.0
  birthday: 03/25
  blood_type: O
  handedness: right
  hobbies:
  - "オセロ"
  - "野球"
  talents:
  - "節約"
  - "家庭菜園"
  favorites:
  - "家族"
  color: "#f39939"
makoto:
  idol_id: 6
  idol_type: Da
  name:
    family: "菊地"
    family_kana: "きくち"
    given: "真"
    given_kana: "まこと"
    shorten: "真"
  age: 17
  height: 159.0
  weight: 44.0
  bust: 75.0
  waist: 57.0
  hip: 78.0
  birthday: 08/29
  blood_type: O
  handedness: right
  hobbies:
  - "スポーツ全般"
  talents:
  - "空手"
  - "ダンス"
  favorites:
  - "ぬいぐるみ"
  color: "#515558"
iori:
  idol_id: 7
  idol_type: Vo
  name:
    family: "水瀬"
    family_kana: "みなせ"
    given: "伊織"
    given_kana: "いおり"
    shorten: "伊織"
  age: 15
  height: 153.0
  weight: 40.0
  bust: 77.0
  waist: 54.0
  hip: 79.0
  birthday: 05/05
  blood_type: AB
  handedness: right
  hobbies:
  - "海外旅行"
  - "食べ歩き"
  talents:
  - "ショッピング"
  favorites:
  - "果汁100％オレンジジュース"
  color: "#fd99e1"
takane:
  idol_id: 8
  idol_type: Vo
  name:
    family: "四条"
    family_kana: "しじょう"
    given: "貴音"
    given_kana: "たかね"
    shorten: "貴音"
  age: 18
  height: 169.0
  weight: 49.0
  bust: 90.0
  waist: 62.0
  hip: 92.0
  birthday: 01/21
  blood_type: B
  handedness: right
  hobbies:
  - "天体観測"
  - "歴史"
  talents:
  - "直感"
  favorites:
  - "ラーメン"
  color: "#a6126a"
ritsuko:
  idol_id: 9
  idol_type: Vi
  name:
    family: "秋月"
    family_kana: "あきづき"
    given: "律子"
    given_kana: "りつこ"
    shorten: "律子"
  age: 19
  height: 156.0
  weight: 43.0
  bust: 85.0
  waist: 57.0
  hip: 85.0
  birthday: 06/23
  blood_type: A
  handedness: right
  hobbies:
  - "資格取得"
  talents:
  - "分析・実践"
  favorites:
  - "ゲーム"
  - "小説"
  color: "#01a860"
azusa:
  idol_id: 10
  idol_type: Vo
  name:
    family: "三浦"
    family_kana: "みうら"
    given: "あずさ"
    given_kana: "あずさ"
    shorten: "あずさ"
  age: 21
  height: 168.0
  weight: 48.0
  bust: 91.0
  waist: 59.0
  hip: 86.0
  birthday: 07/19
  blood_type: O
  handedness: right
  hobbies:
  - "犬の散歩"
  talents:
  - "占い"
  favorites:
  - "カフェ巡り"
  color: "#9238be"
ami:
  idol_id: 11
  idol_type: Vi
  name:
    family: "双海"
    family_kana: "ふたみ"
    given: "亜美"
    given_kana: "あみ"
    shorten: "亜美"
  age: 13
  height: 158.0
  weight: 42.0
  bust: 78.0
  waist: 55.0
  hip: 77.0
  birthday: 05/22
  blood_type: B
  handedness: right
  hobbies:
  - "メール"
  - "エコ"
  talents:
  - "モノマネ"
  favorites:
  - "遊ぶこと"
  color: "#ffe43f"
mami:
  idol_id: 12
  idol_type: Vi
  name:
    family: "双海"
    family_kana: "ふたみ"
    given: "真美"
    given_kana: "まみ"
    shorten: "真美"
  age: 13
  height: 158.0
  weight: 42.0
  bust: 78.0
  waist: 55.0
  hip: 77.0
  birthday: 05/22
  blood_type: B
  handedness: left
  hobbies:
  - "メール"
  - "ゲーム"
  talents:
  - "モノマネ"
  favorites:
  - "遊ぶこと"
  color: "#ffe43f"
hibiki:
  idol_id: 13
  idol_type: Da
  name:
    family: "我那覇"
    family_kana: "がなは"
    given: "響"
    given_kana: "ひびき"
    shorten: "響"
  age: 16
  height: 152.0
  weight: 41.0
  bust: 83.0
  waist: 56.0
  hip: 80.0
  birthday: 10/10
  blood_type: A
  handedness: right
  hobbies:
  - "編み物"
  - "卓球"
  talents:
  - "家事全般"
  favorites:
  - "散歩"
  - "動物"
  color: "#01adb9"
mirai:
  idol_id: 14
  idol_type: Vo
  name:
    family: "春日"
    family_kana: "かすが"
    given: "未来"
    given_kana: "みらい"
    shorten: "未来"
  age: 14
  height: 156.0
  weight: 42.0
  bust: 78.0
  waist: 54.0
  hip: 77.0
  birthday: 06/28
  blood_type: O
  handedness: right
  hobbies:
  - "可愛い髪留めを集めること"
  talents:
  - "歌うこと"
  favorites:
  - "ライブ"
  color: "#ea5b76"
shizuka:
  idol_id: 15
  idol_type: Vo
  name:
    family: "最上"
    family_kana: "もがみ"
    given: "静香"
    given_kana: "しずか"
    shorten: "静香"
  age: 14
  height: 162.0
  weight: 44.0
  bust: 76.0
  waist: 53.0
  hip: 77.0
  birthday: 09/14
  blood_type: A
  handedness: right
  hobbies:
  - "テニス"
  talents:
  - "ピアノ"
  favorites:
  - "うどん"
  color: "#6495cf"
tsubasa:
  idol_id: 16
  idol_type: Vi
  name:
    family: "伊吹"
    family_kana: "いぶき"
    given: "翼"
    given_kana: "つばさ"
    shorten: "翼"
  age: 14
  height: 158.0
  weight: 43.0
  bust: 85.0
  waist: 52.0
  hip: 82.0
  birthday: 07/30
  blood_type: B
  handedness: left
  hobbies:
  - "遊びの計画をたてること"
  talents:
  - "じゃんけん"
  favorites:
  - "ビーフステーキ"
  color: "#fed552"
kotoha:
  idol_id: 17
  idol_type: Vo
  name:
    family: "田中"
    family_kana: "たなか"
    given: "琴葉"
    given_kana: "ことは"
    shorten: "琴葉"
  age: 18
  height: 157.0
  weight: 44.0
  bust: 79.0
  waist: 55.0
  hip: 78.0
  birthday: 10/05
  blood_type: A
  handedness: right
  hobbies:
  - "お風呂"
  talents:
  - "フェンシング"
  favorites:
  - "アイス"
  color: "#92cfbb"
erena:
  idol_id: 18
  idol_type: Da
  name:
    family: "島原"
    family_kana: "しまばら"
    given: "エレナ"
    given_kana: "えれな"
    shorten: "エレナ"
  age: 17
  height: 160.0
  weight: 47.0
  bust: 85.0
  waist: 58.0
  hip: 86.0
  birthday: 10/26
  blood_type: B
  handedness: right
  hobbies:
  - "パーティー"
  talents:
  - "サンバを踊ること"
  favorites:
  - "みんなで騒ぐこと"
  color: "#9bce92"
minako:
  idol_id: 19
  idol_type: Da
  name:
    family: "佐竹"
    family_kana: "さたけ"
    given: "美奈子"
    given_kana: "みなこ"
    shorten: "美奈子"
  age: 18
  height: 158.0
  weight: 45.0
  bust: 86.0
  waist: 54.0
  hip: 82.0
  birthday: 03/22
  blood_type: O
  handedness: right
  hobbies:
  - "格闘ゲーム"
  talents:
  - "料理"
  favorites:
  - "友達との長電話"
  color: "#58a6dc"
megumi:
  idol_id: 20
  idol_type: Vi
  name:
    family: "所"
    family_kana: "ところ"
    given: "恵美"
    given_kana: "めぐみ"
    shorten: "恵美"
  age: 16
  height: 159.0
  weight: 47.0
  bust: 88.0
  waist: 56.0
  hip: 85.0
  birthday: 04/15
  blood_type: O
  handedness: right
  hobbies:
  - "カラオケ"
  talents:
  - "人の誕生日を覚えること"
  favorites:
  - "友達"
  color: "#454341"
matsuri:
  idol_id: 21
  idol_type: Vi
  name:
    family: "徳川"
    family_kana: "とくがわ"
    given: "まつり"
    given_kana: "まつり"
    shorten: "まつり"
  age: 19
  height: 163.0
  weight: 44.0
  bust: 85.0
  waist: 59.0
  hip: 85.0
  birthday: 02/04
  blood_type: AB
  handedness: right
  hobbies:
  - "漫画あつめ"
  talents:
  - "演技"
  favorites:
  - "焼きマシュマロ"
  - "ウミウシ"
  color: "#5abfb7"
serika:
  idol_id: 22
  idol_type: Vo
  name:
    family: "箱崎"
    family_kana: "はこざき"
    given: "星梨花"
    given_kana: "せりか"
    shorten: "星梨花"
  age: 13
  height: 146.0
  weight: 37.0
  bust: 74.0
  waist: 54.0
  hip: 76.0
  birthday: 02/20
  blood_type: O
  handedness: right
  hobbies:
  - "バイオリン"
  talents:
  - "アジリティのハンドラー"
  favorites:
  - "紅茶"
  - "クッキー"
  color: "#ed90ba"
akane:
  idol_id: 23
  idol_type: Da
  name:
    family: "野々原"
    family_kana: "ののはら"
    given: "茜"
    given_kana: "あかね"
    shorten: "茜"
  age: 16
  height: 150.0
  weight: 42.0
  bust: 80.0
  waist: 58.0
  hip: 79.0
  birthday: 12/03
  blood_type: AB
  handedness: left
  hobbies:
  - "スキップ"
  talents:
  - "インラインスケート"
  favorites:
  - "プリン"
  color: "#eb613f"
anna:
  idol_id: 24
  idol_type: Vo
  name:
    family: "望月"
    family_kana: "もちづき"
    given: "杏奈"
    given_kana: "あんな"
    shorten: "杏奈"
  age: 14
  height: 152.0
  weight: 41.0
  bust: 78.0
  waist: 53.0
  hip: 79.0
  birthday: 05/31
  blood_type: AB
  handedness: right
  hobbies:
  - "オンラインゲーム"
  talents:
  - "タイピング"
  favorites:
  - "かわいいもの"
  color: "#7e6ca8"
roko:
  idol_id: 25
  idol_type: Vi
  name:
    aka: "ロコ"
    family: "伴田"
    family_kana: "はんだ"
    given: "路子"
    given_kana: "ろこ"
    shorten: "ロコ"
  age: 15
  height: 154.0
  weight: 42.0
  bust: 78.0
  waist: 57.0
  hip: 77.0
  birthday: 03/01
  blood_type: AB
  handedness: right
  hobbies:
  - "物を作ること"
  talents:
  - "目を閉じたまま歩ける"
  favorites:
  - "ハト"
  color: "#fff03c"
yuriko:
  idol_id: 26
  idol_type: Vi
  name:
    family: "七尾"
    family_kana: "ななお"
    given: "百合子"
    given_kana: "ゆりこ"
    shorten: "百合子"
  age: 15
  height: 154.0
  weight: 41.0
  bust: 78.0
  waist: 56.0
  hip: 80.0
  birthday: 03/18
  blood_type: B
  handedness: right
  hobbies:
  - "読書"
  talents:
  - "ペン回し"
  favorites:
  - "おはぎ"
  color: "#c7b83c"
sayoko:
  idol_id: 27
  idol_type: Vo
  name:
    family: "高山"
    family_kana: "たかやま"
    given: "紗代子"
    given_kana: "さよこ"
    shorten: "紗代子"
  age: 17
  height: 156.0
  weight: 42.0
  bust: 82.0
  waist: 55.0
  hip: 80.0
  birthday: 12/29
  blood_type: A
  handedness: right
  hobbies:
  - "ハリネズミの飼育"
  talents:
  - "一晩寝ると元気になれる"
  favorites:
  - "友達"
  - "アイドル仲間"
  color: "#7f6575"
arisa:
  idol_id: 28
  idol_type: Vo
  name:
    family: "松田"
    family_kana: "まつだ"
    given: "亜利沙"
    given_kana: "ありさ"
    shorten: "亜利沙"
  age: 16
  height: 154.0
  weight: 40.0
  bust: 81.0
  waist: 54.0
  hip: 80.0
  birthday: 06/07
  blood_type: AB
  handedness: right
  hobbies:
  - "アイドルのデータ集め"
  talents:
  - "アイドルの変装を見破れる"
  favorites:
  - "ファミレスのデザート"
  color: "#b54461"
umi:
  idol_id: 29
  idol_type: Da
  name:
    family: "高坂"
    family_kana: "こうさか"
    given: "海美"
    given_kana: "うみ"
    shorten: "海美"
  age: 16
  height: 155.0
  weight: 45.0
  bust: 82.0
  waist: 57.0
  hip: 84.0
  birthday: 08/10
  blood_type: O
  handedness: right
  hobbies:
  - "ボルダリング"
  talents:
  - "常人にできないポージングができる"
  favorites:
  - "ダンス"
  color: "#e9739b"
iku:
  idol_id: 30
  idol_type: Vi
  name:
    family: "中谷"
    family_kana: "なかたに"
    given: "育"
    given_kana: "いく"
    shorten: "育"
  age: 10
  height: 142.0
  weight: 37.0
  bust: 72.0
  waist: 52.0
  hip: 73.0
  birthday: 12/16
  blood_type: B
  handedness: right
  hobbies:
  - "アニメ鑑賞"
  talents:
  - "早起き"
  favorites:
  - "おかあさん"
  color: "#f7e78e"
tomoka:
  idol_id: 31
  idol_type: Vo
  name:
    family: "天空橋"
    family_kana: "てんくうばし"
    given: "朋花"
    given_kana: "ともか"
    shorten: "朋花"
  age: 15
  height: 156.0
  weight: 41.0
  bust: 80.0
  waist: 56.0
  hip: 79.0
  birthday: 11/11
  blood_type: AB
  handedness: left
  hobbies:
  - "ファンに喜んでもらうこと"
  talents:
  - "口げんか"
  favorites:
  - "かわいい扇子"
  color: "#bee3e3"
emily:
  idol_id: 32
  idol_type: Da
  name:
    family: "エミリー"
    family_kana: "えみりー"
    given: "スチュアート"
    given_kana: "すちゅあーと"
    shorten: "エミリー"
  age: 13
  height: 156.0
  weight: 41.0
  bust: 74.0
  waist: 54.0
  hip: 76.0
  birthday: 01/08
  blood_type: A
  handedness: right
  hobbies:
  - "かるた遊び"
  talents:
  - "日本舞踊"
  favorites:
  - "抹茶"
  color: "#554171"
shiho:
  idol_id: 33
  idol_type: Vi
  name:
    family: "北沢"
    family_kana: "きたざわ"
    given: "志保"
    given_kana: "しほ"
    shorten: "志保"
  age: 14
  height: 161.0
  weight: 46.0
  bust: 83.0
  waist: 56.0
  hip: 84.0
  birthday: 01/18
  blood_type: A
  handedness: right
  hobbies:
  - "お気に入りの絵本を探すこと"
  talents:
  - "記憶力"
  - "集中力が高い"
  favorites:
  - "ぬいぐるみ"
  color: "#afa690"
ayumu:
  idol_id: 34
  idol_type: Da
  name:
    family: "舞浜"
    family_kana: "まいはま"
    given: "歩"
    given_kana: "あゆむ"
    shorten: "歩"
  age: 19
  height: 158.0
  weight: 49.9
  bust: 86.0
  waist: 60.0
  hip: 88.0
  birthday: 07/23
  blood_type: A
  handedness: right
  hobbies:
  - "ショッピング"
  talents:
  - "ダンス"
  favorites:
  - "わさび"
  color: "#e25a9b"
hinata:
  idol_id: 35
  idol_type: Vo
  name:
    family: "木下"
    family_kana: "きのした"
    given: "ひなた"
    given_kana: "ひなた"
    shorten: "ひなた"
  age: 14
  height: 146.0
  weight: 39.5
  bust: 74.0
  waist: 55.0
  hip: 78.0
  birthday: 07/04
  blood_type: O
  handedness: right
  hobbies:
  - "ガーデニング"
  talents:
  - "天気を当てること"
  favorites:
  - "おばあちゃん"
  color: "#d1342c"
kana:
  idol_id: 36
  idol_type: Vo
  name:
    family: "矢吹"
    family_kana: "やぶき"
    given: "可奈"
    given_kana: "かな"
    shorten: "可奈"
  age: 14
  height: 155.0
  weight: 43.0
  bust: 77.0
  waist: 54.0
  hip: 76.0
  birthday: 08/18
  blood_type: A
  handedness: right
  hobbies:
  - "なんでも歌にすること"
  talents:
  - "合唱"
  favorites:
  - "屋上で歌うこと"
  color: "#f5ad3b"
nao:
  idol_id: 37
  idol_type: Da
  name:
    family: "横山"
    family_kana: "よこやま"
    given: "奈緒"
    given_kana: "なお"
    shorten: "奈緒"
  age: 17
  height: 159.0
  weight: 46.0
  bust: 84.0
  waist: 57.0
  hip: 83.0
  birthday: 02/12
  blood_type: O
  handedness: right
  hobbies:
  - "銭湯＆温泉巡り"
  talents:
  - "スタミナがある"
  favorites:
  - "友達とおしゃべり"
  color: "#788bc5"
chiduru:
  idol_id: 38
  idol_type: Vi
  name:
    family: "二階堂"
    family_kana: "にかいどう"
    given: "千鶴"
    given_kana: "ちづる"
    shorten: "千鶴"
  age: 21
  height: 165.0
  weight: 50.0
  bust: 85.0
  waist: 58.0
  hip: 86.0
  birthday: 10/21
  blood_type: B
  handedness: right
  hobbies:
  - "カフェでアパレル誌チェック"
  talents:
  - "人の名前と顔を忘れない"
  favorites:
  - "憧れの目で見られること"
  color: "#f19557"
konomi:
  idol_id: 39
  idol_type: Da
  name:
    family: "馬場"
    family_kana: "ばば"
    given: "このみ"
    given_kana: "このみ"
    shorten: "このみ"
  age: 24
  height: 143.0
  weight: 37.0
  bust: 75.0
  waist: 55.0
  hip: 79.0
  birthday: 06/12
  blood_type: A
  handedness: right
  hobbies:
  - "北米ドラマ鑑賞"
  talents:
  - "麻雀"
  favorites:
  - "日本酒"
  color: "#f1becb"
tamaki:
  idol_id: 40
  idol_type: Da
  name:
    family: "大神"
    family_kana: "おおがみ"
    given: "環"
    given_kana: "たまき"
    shorten: "環"
  age: 12
  height: 147.0
  weight: 39.0
  bust: 76.0
  waist: 51.0
  hip: 77.0
  birthday: 04/29
  blood_type: B
  handedness: right
  hobbies:
  - "探検"
  talents:
  - "石投げ"
  favorites:
  - "アスレチックランド"
  color: "#ee762e"
fuuka:
  idol_id: 41
  idol_type: Vi
  name:
    family: "豊川"
    family_kana: "とよかわ"
    given: "風花"
    given_kana: "ふうか"
    shorten: "風花"
  age: 22
  height: 162.0
  weight: 51.0
  bust: 93.0
  waist: 63.0
  hip: 91.0
  birthday: 09/02
  blood_type: O
  handedness: right
  hobbies:
  - "献血"
  talents:
  - "息を止めること"
  favorites:
  - "猫"
  color: "#7278a8"
miya:
  idol_id: 42
  idol_type: Vi
  name:
    family: "宮尾"
    family_kana: "みやお"
    given: "美也"
    given_kana: "みや"
    shorten: "美也"
  age: 17
  height: 156.0
  weight: 46.0
  bust: 84.0
  waist: 58.0
  hip: 83.0
  birthday: 04/24
  blood_type: O
  handedness: right
  hobbies:
  - "囲碁"
  - "将棋"
  talents:
  - "視力が高い"
  favorites:
  - "サンドイッチ"
  color: "#d7a96b"
noriko:
  idol_id: 43
  idol_type: Da
  name:
    family: "福田"
    family_kana: "ふくだ"
    given: "のり子"
    given_kana: "のりこ"
    shorten: "のり子"
  age: 18
  height: 164.0
  weight: 48.0
  bust: 87.0
  waist: 58.0
  hip: 87.0
  birthday: 03/30
  blood_type: A
  handedness: right
  hobbies:
  - "格闘技観戦"
  talents:
  - "バイクの運転"
  favorites:
  - "焼肉"
  color: "#eceb70"
mizuki:
  idol_id: 44
  idol_type: Da
  name:
    family: "真壁"
    family_kana: "まかべ"
    given: "瑞希"
    given_kana: "みずき"
    shorten: "瑞希"
  age: 17
  height: 160.0
  weight: 43.0
  bust: 73.0
  waist: 54.0
  hip: 77.0
  birthday: 01/27
  blood_type: B
  handedness: right
  hobbies:
  - "手品"
  talents:
  - "バトントワリング"
  favorites:
  - "クロスワードパズル"
  color: "#99b7dc"
karen:
  idol_id: 45
  idol_type: Vi
  name:
    family: "篠宮"
    family_kana: "しのみや"
    given: "可憐"
    given_kana: "かれん"
    shorten: "可憐"
  age: 16
  height: 159.0
  weight: 48.0
  bust: 90.0
  waist: 59.0
  hip: 90.0
  birthday: 08/27
  blood_type: AB
  handedness: right
  hobbies:
  - "アロマテラピー"
  talents:
  - "ポーカーフェイス"
  favorites:
  - "お風呂"
  color: "#b63b40"
rio:
  idol_id: 46
  idol_type: Da
  name:
    family: "百瀬"
    family_kana: "ももせ"
    given: "莉緒"
    given_kana: "りお"
    shorten: "莉緒"
  age: 23
  height: 168.0
  weight: 46.0
  bust: 84.0
  waist: 57.0
  hip: 84.0
  birthday: 11/21
  blood_type: A
  handedness: right
  hobbies:
  - "ヨガエクササイズ"
  talents:
  - "メイク"
  favorites:
  - "可愛くてセクシーな服"
  color: "#f19591"
subaru:
  idol_id: 47
  idol_type: Da
  name:
    family: "永吉"
    family_kana: "ながよし"
    given: "昴"
    given_kana: "すばる"
    shorten: "昴"
  age: 15
  height: 154.0
  weight: 41.0
  bust: 79.0
  waist: 59.0
  hip: 78.0
  birthday: 09/20
  blood_type: B
  handedness: left
  hobbies:
  - "野球"
  talents:
  - "変化球"
  favorites:
  - "アイドル"
  color: "#aeb49c"
reika:
  idol_id: 48
  idol_type: Da
  name:
    family: "北上"
    family_kana: "きたかみ"
    given: "麗花"
    given_kana: "れいか"
    shorten: "麗花"
  age: 20
  height: 164.0
  weight: 47.0
  bust: 84.0
  waist: 58.0
  hip: 84.0
  birthday: 05/17
  blood_type: A
  handedness: right
  hobbies:
  - "登山"
  talents:
  - "肺活量が大きい"
  favorites:
  - "ドライブ"
  color: "#6bb6b0"
momoko:
  idol_id: 49
  idol_type: Vi
  name:
    family: "周防"
    family_kana: "すおう"
    given: "桃子"
    given_kana: "ももこ"
    shorten: "桃子"
  age: 11
  height: 140.0
  weight: 35.0
  bust: 73.0
  waist: 53.0
  hip: 74.0
  birthday: 11/06
  blood_type: B
  handedness: right
  hobbies:
  - "かわいいシール集め"
  talents:
  - "演技や台詞の暗記"
  favorites:
  - "ホットケーキ"
  color: "#efb864"
juria:
  idol_id: 50
  idol_type: Vo
  name:
    aka: "ジュリア"
    shorten: "ジュリア"
  age: 16
  height: 157.0
  weight: 43.0
  bust: 79.0
  waist: 54.0
  hip: 80.0
  birthday: 09/26
  blood_type: O
  handedness: left
  hobbies:
  talents:
  - "ギター"
  favorites:
  - "パンクロック"
  color: "#d7385f"
